<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="WarningService" targetNamespace="http://enav.frv.dk/msi/ws/warning"
                  xmlns:ns1="http://message.webservice.core.msiedit.frv.dk/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://enav.frv.dk/msi/ws/warning" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        >
    <wsdl:import location="MsiService.wsdl"
                 namespace="http://message.webservice.core.msiedit.frv.dk/">
    </wsdl:import>
    <wsdl:binding name="WarningServiceSoapBinding" type="ns1:MsiService">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getActiveWarningCountry">
            <soap:operation soapAction="" style="rpc"/>
            <wsdl:input name="getActiveWarningCountry">
                <soap:body namespace="http://message.webservice.core.msiedit.frv.dk/" use="literal"/>
            </wsdl:input>
            <wsdl:output name="getActiveWarningCountryResponse">
                <soap:body namespace="http://message.webservice.core.msiedit.frv.dk/" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getActiveWarning">
            <soap:operation soapAction="" style="rpc"/>
            <wsdl:input name="getActiveWarning">
                <soap:body namespace="http://message.webservice.core.msiedit.frv.dk/" use="literal"/>
            </wsdl:input>
            <wsdl:output name="getActiveWarningResponse">
                <soap:body namespace="http://message.webservice.core.msiedit.frv.dk/" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="getWarningAfterId">
            <soap:operation soapAction="" style="rpc"/>
            <wsdl:input name="getWarningAfterId">
                <soap:body namespace="http://message.webservice.core.msiedit.frv.dk/" use="literal"/>
            </wsdl:input>
            <wsdl:output name="getWarningAfterIdResponse">
                <soap:body namespace="http://message.webservice.core.msiedit.frv.dk/" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="WarningService">
        <wsdl:port binding="tns:WarningServiceSoapBinding" name="MsiServiceBeanPort">
            <soap:address location="http://msi-beta.e-navigation.net/msi/ws/warning"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>