;/* Version 14ddc6154b98c5cd1e0fdee29556261f v:4.0.0.3, c:1b4cfe7b9828f28796fa1ca312fceb1ef8b34c20, b:7451 n:28-4.0.0.next */(function(){(function(){if(!window.ADRUM&&!0!==window["adrum-disable"]){var a=window.ADRUM={};window["adrum-start-time"]=window["adrum-start-time"]||(new Date).getTime();(function(b){b.beaconUrlHttp="http://col.eum-appdynamics.com";b.beaconUrlHttps="https://col.eum-appdynamics.com";b.appKey=window["adrum-app-key"]||"AD-AAB-AAA-RVX";var c="https:"===document.location.protocol;if(window["adrum-geo-resolver-url"]){var e=window["adrum-geo-resolver-url"],d=e.indexOf("://");-1!=d&&(e=e.substring(d+3));e=(c?"https://":"http://")+e}else e=
c?"":"";b.adrumExtUrl=(c?"https://de8of677fyt0b.cloudfront.net":"http://de8of677fyt0b.cloudfront.net")+"/adrum-ext.14ddc6154b98c5cd1e0fdee29556261f.js";b.sendImageBeacon="false";b.geoResolverUrl=e;b.useStrictDomainCookies=!0===window["adrum-use-strict-domain-cookies"];b.k;(function(b){function e(b){return 0<=b.location.search.indexOf("ADRUM_debug=true")||0<=b.cookie.search(/(^|;)\s*ADRUM_debug=true/)}b.sd=e;b.iDR=e})(b.a||(b.a={}));b.isDebug="false"})(a||(a={}));
(function(b){b.logMessages=[];b.debug;b.warn;b.info;b.error;for(var c=["debug","warn","info","error"],e=0;e<c.length;e++)(function(e){b[e]=function(z,d){b.isDebug&&b.logMessages.push([e,Array.prototype.slice.call(arguments).join(" | ")])}})(c[e]);var d=0;(function(e){window.ADRUM.TPL=e;e.ea=function(b,e,z,m){b=z+"/eumcollector/error.gif?version=1&appKey="+m+"&msg="+encodeURIComponent(b.substring(0,500));e&&(b+="&stack=",b+=encodeURIComponent(e.substring(0,1500-b.length)));return b};e.cIEBU=e.ea;e.p=
function(z,c){2<=d||((new Image).src=e.ea(z,c,b.beaconUrlHttps,b.appKey),d++)};e.dumpLog=b.isDebug?function(){for(var e="",z=0;z<b.logMessages.length;z++)var m=b.logMessages[z],e=e+("["+m[0]+"]\t"+m[1].replace(RegExp("<br/>","g"),"\n\t")+"\n");return e}:function(){}})(b.a||(b.a={}));var A=b.a,z=b.error;b.error=function(){for(var b=0;b<arguments.length-0;b++);0<arguments.length&&(b=Array.prototype.slice.call(arguments).join(" | "),z(b),A.p(b,null))};b.exception=function(){if(!(1>arguments.length)){var b=
Array.prototype.slice.call(arguments),e;e=(e=b[0])?(e=e.stack)&&"string"===typeof e?e:null:null;b=b.slice(1).join(" | ");z(b);A.p(b,e)}};b.assert=function(e,z){e||b.error("Assert fail: "+z)};b.info("M0")})(a||(a={}));(function(b){(function(c){var e=function(){function e(){this.Eb=[];this.Za(e.jb,0)}e.prototype.Wa=function(b){this.Za(e.Qb,b)};e.prototype.tb=function(b){this.Za(e.Tb,b)};e.prototype.Xa=function(b){this.Za(e.Rb,b)};e.prototype.Za=function(b,e){this.Eb.push({yd:(new Date).getTime(),xd:e,
jc:b});this.dd=b};e.prototype.getPhaseID=function(b){for(var z=0;z<e.Sb.length;z++)if(e.Sb[z]===b)return z;return null};e.prototype.getPhaseCallbackTime=function(b){for(var e=this.Eb,m=0;m<e.length;m++)if(e[m].jc===b)return e[m].yd;return null};e.prototype.findPhaseAtNominalTime=function(c){b.assert(0<=c);for(var z=this.Eb,m=z.length-1;0<=m;m--)if(c>=z[m].xd)return z[m].jc;b.error("M1",c,b.EXT.Wb(z));return e.jb};e.jb="AFTER_FIRST_BYTE";e.Qb="AFTER_DOM_INTERACTIVE";e.Tb="AT_ONLOAD";e.Rb="AFTER_ONLOAD";
e.Sb=[e.jb,e.Qb,e.Tb,e.Rb];return e}();c.Qa=e})(b.a||(b.a={}))})(a||(a={}));(function(b){(function(c){c.nc=function(b){setTimeout(b,0)};c.bd=function(){b.navTiming=null;var e=window.performance||window.f||window.g||window.i;if(e&&e.timing)if(e=e.timing,e.navigationStart&&e.navigationStart<=e.loadEventEnd){var c={},A;for(A in e){var z=e[A];"number"===typeof z&&(c[A]=z)}b.navTiming=c}else b.debug("M2")};c.cd=function(){b.resTiming=null;var e=window.performance||window.f||window.g||window.i;e&&e.getEntriesByType&&
((e=e.getEntriesByType("resource"))&&e.length&&0!==e.length&&e.unshift?(b.resTiming=e,b.navTiming?(e=b.navTiming,e.initiatorType="other",e.name=document.URL,e.navigationStart&&!e.startTime&&(e.startTime=e.navigationStart),e.isBase=!0):e=null,e&&b.resTiming.unshift(e)):b.debug("M3"))}})(b.a||(b.a={}))})(a||(a={}));(function(b){(function(b){b.eb=100})(b.a||(b.a={}));var c=b.a;b.q=[];b.isDead=!1;b.command=function(e,d){b.isDebug&&b.debug("M4",e,Array.prototype.slice.call(arguments).slice(1).join(", "));
b.isDead?b.debug("M5"):b.q.length>=c.eb?(b.info("M6"),b.q=[],b.isDead=!0):(b.q.push(Array.prototype.slice.call(arguments)),b.EXT&&b.EXT.processQ&&b.initEXTDone&&b.EXT.processQ())}})(a||(a={}));(function(b){(function(c){window.ADRUM.aop=c;c.support=function(b){return!b||"apply"in b};c.around=function(e,d,A,z){b.assert(c.support(e),"aop.around called on a function which does not support interception");e=e||function(){};return function(){b.isDebug&&b.debug("M7",z,Array.prototype.slice.call(arguments).join(", "));
var m=Array.prototype.slice.call(arguments),c;try{d&&(c=d.apply(this,m))}catch(l){b.exception(l,"M8",z,l)}b.assert(!c||"[object Array]"===Object.prototype.toString.call(c));var a=void 0;try{a=e.apply(this,c||m)}finally{try{A&&A.apply(this,m)}catch(n){b.exception(n,"M9",z,n)}}return a}};c.before=function(b,d){return c.around(b,d)};c.after=function(b,d){return c.around(b,null,d)}})(b.b||(b.b={}))})(a||(a={}));(function(b){b.initEXTDone=!1;b.addEventListener=function(c,e,d){function A(){try{return d.apply(this,
Array.prototype.slice.call(arguments))}catch(z){b.exception(z,"M11",e,c,z)}}b.isDebug&&b.debug("M10",e,c);c.addEventListener?c.addEventListener(e,A,!1):c.attachEvent&&c.attachEvent("on"+e,A)};b.compareWindows=function(b,e){return b==e};b.lifecycle=new b.a.Qa;b.listenForErrors=null;(function(){var c=!1;b.listenForErrors=function(){b.b.support(window.onerror)?(window.onerror=b.b.around(window.onerror,function(e,d,A){c||b.command("reportError",e,d,A);c=!0},function(){c=!1},"onerror"),b.windowErrorHandler=
window.onerror,b.info("M12")):b.info("M13")}})();b.windowErrorHandler=window.onerror;b.navTiming=null;b.resTiming=null;b.j=function(c){b.lifecycle.tb(c&&c.timeStamp);b.a.nc(function(){var e=(new Date).getTime();b.lifecycle.Xa(e);b.command("mark","onload",e);b.a.bd();b.a.cd();b.command("reportOnload");b.e()});b.info("M14")};b.h=function(){function c(b){document.addEventListener?(document.removeEventListener("DOMContentLoaded",c,!1),e(b)):"complete"===document.readyState&&(document.detachEvent("onreadystatechange",
c),e(b))}function e(e){d||(b.lifecycle.Wa(e&&e.timeStamp),b.command("mark","onready",(new Date).getTime()),d=!0)}var d=!1;if(document.addEventListener)document.addEventListener("DOMContentLoaded",c,!1),window.addEventListener("load",e,!1);else{document.attachEvent("onreadystatechange",c);window.attachEvent("onload",e);var A=null;try{A=null===window.frameElement?document.documentElement:null}catch(z){}null!=A&&A.doScroll&&function h(){try{A.doScroll("left")}catch(b){setTimeout(h,10);return}e()}()}b.info("M15")};
b.e=function(){var c=document.createElement("script");c.async=!0;c.src=b.adrumExtUrl;var e=document.getElementsByTagName("script")[0];e?(e.parentNode.insertBefore(c,e),b.info("M16")):b.info("M17")}})(a||(a={}));(function(b){b.startTimeCookie=null;b.cookieMetadataChunks=null;(function(c){c.M=function(e,c){function A(b){var e=[],z=u.exec(b);if(z){b=z[1];var z=z[2].replace(/^"|"$/g,""),z=decodeURIComponent(z).split("|"),c=z[0].split(":");if("R"===c[0]&&Number(c[1])===k)for(a(b),b=1;b<z.length;b++)e.push(z[b])}return e}
function z(b){if(b=n.exec(b)){var e=b[1],z=b[4],c=b[5];if(Number(b[3])===k)return a(e),[Number(z),c]}return null}function m(e){var z=l.exec(e);z&&(b.debug("M20",e),3===z.length?(b.startTimeCookie={startTime:Number(z[1]),startPage:z[2]},a("ADRUM")):b.error("M21",e))}function a(e){b.debug("M19",e);var z=new Date;z.setTime(z.getTime()-1E3);document.cookie=e+"=;Expires="+z.toUTCString()}b.info("M18");for(var l=/^\s*ADRUM=s=([\d]+)&r=(.*)\s*/,k=c?c.length:0,n=/^\s*(ADRUM_(\d+)_(\d+)_(\d+))=(.*)\s*$/i,
p=[],q=e.split(";"),r=0;r<q.length;r++){var s=q[r],t=z(s);t?p.push(t):m(s)}Array.prototype.sort.call(p,function(b,e){return b[0]-e[0]});s=[];for(r=0;r<p.length;r++)s.push(p[r][1]);for(var u=/^\s*(ADRUM_BT\w*)=(.*)\s*$/i,r=0;r<q.length;r++)(p=A(q[r]))&&0<p.length&&(s=s.concat(p));b.cookieMetadataChunks=s};c.eck=c.M})(b.a||(b.a={}))})(a||(a={}));(function(b){(function(e){e.Ub=function(){return function(e,a){if(("load"===e||"error"===e)&&a&&this._adrumXhrData){var z;z=a;if(z.__adrumInterceptor)z=z.__adrumInterceptor;
else if(b.b.support(z)){var m=c.Vb(z,this,"XHR.invokeEventListener");z=z.__adrumInterceptor=m}else z=null;if(z)return m=Array.prototype.slice.call(arguments),m[1]=z,b.debug("M22"),m;b.debug("M23",e,a)}}}})(b.a||(b.a={}));(function(e){if(!0===window["adrum-xhr-disable"])b.info("M24");else if(window.XMLHttpRequest)if(e.I=window.XMLHttpRequest.prototype,e.I)if("open"in e.I&&"send"in e.I)if(b.b.support(e.I.open)&&b.b.support(e.I.send)){b.info("M29");b.xhrOpen=e.I.open;b.xhrSend=e.I.send;e.bc=function(e){var c=
e._adrumXhrData;if(c){var a=(new Date).getTime();2==e.readyState?c.firstByteTime=c.firstByteTime||a:4==e.readyState&&(b.assert(null===c.respAvailTime,"M30"),c.respAvailTime=c.respAvailTime||a,c.firstByteTime=c.firstByteTime||a)}};e.d=function(e,c){var a=e.getAllResponseHeaders(),l=e.status;b.command("reportXhr",c,a,l,400<=l?e.responseText:null)};e.Vb=function(z,m,a){return c(z,function(){e.bc(this)},function(){var z=m._adrumXhrData;if(z&&4==m.readyState){var c=(new Date).getTime();b.assert(null===
z.respProcTime,"M31");z.respProcTime=z.respProcTime||c;e.d(m,z);delete m._adrumXhrData}},a)};e.ab=function(z){if(z._adrumXhrData){var c=(new Date).getTime()+3E4,a=function(){e.bc(z);var d=z._adrumXhrData;if(d){var A=(new Date).getTime();4==z.readyState?(b.assert(null===d.respProcTime,"M32"),d.respProcTime=d.respProcTime||A,b.debug("M33"),e.d(z,d),delete z._adrumXhrData):A<c?setTimeout(a,50):(delete z._adrumXhrData,b.debug("M34"))}};a()}};var c=function(e,c,a,d){var A=e;e&&"object"===typeof e&&"toString"in
e&&"[xpconnect wrapped nsIDOMEventListener]"===e.toString()&&"handleEvent"in e&&(A=function(){e.handleEvent.apply(this,Array.prototype.slice.call(arguments))});return b.b.around(A,c,a,d)};e.I.open=b.b.around(e.I.open,function(){this._adrumXhrData={url:2<=arguments.length?String(arguments[1]):"",sendTime:null,firstByteTime:null,respAvailTime:null,respProcTime:null,parentPhase:null}},null,"XHR.open");var a=function(b){var e=document.createElement("a");e.href=b;b=document.location;return":"===e.protocol&&
""===e.hostname&&""===e.port||e.protocol===b.protocol&&e.hostname===b.hostname&&e.port===b.port};e.I.send=b.b.around(e.I.send,function(){var z=this,c=z._adrumXhrData;if(c){var d=(new Date).getTime();b.assert(null===c.sendTime,"M35");c.sendTime=c.sendTime||d;c.parentPhase=b.lifecycle.dd;a(c.url)?z.setRequestHeader("ADRUM","isAjax:true"):b.debug("M36",document.location.href,c.url);var l=0,k=function(){if(4==z.readyState)b.debug("M37"),e.ab(z);else{var c=null;try{c=z.onreadystatechange}catch(a){b.debug("M38",
a);e.ab(z);return}l++;c?b.b.support(c)?(z.onreadystatechange=e.Vb(c,z,"XHR.onReadyStateChange"),b.debug("M39",l)):(b.debug("M40"),e.ab(z)):5>l?b.a.nc(k):(b.debug("M41"),e.ab(z))}};k()}},null,"XHR.send");"addEventListener"in e.I&&"removeEventListener"in e.I&&b.b.support(e.I.addEventListener)&&b.b.support(e.I.removeEventListener)?(e.I.addEventListener=b.b.around(e.I.addEventListener,b.a.Ub(),null,"XHR.addEventListener"),e.I.removeEventListener=b.b.around(e.I.removeEventListener,function(e,c){if(this._adrumXhrData){var a=
Array.prototype.slice.call(arguments);c.__adrumInterceptor?(a[1]=c.__adrumInterceptor,b.debug("M42")):b.debug("M43");return a}},null,"XHR.removeEventListener")):b.debug("M44");b.info("M45")}else b.info("M28");else b.info("M27");else b.info("M26");else b.info("M25")})(b.c||(b.c={}));var c=b.c})(a||(a={}));(function(){"APP_KEY_NOT_SET"===window.ADRUM.appKey&&"undefined"!==typeof console&&"undefined"!==typeof console.log&&console.log("AppDynamics EUM cloud application key missing. Please specify window['adrum-app-key']");
var b=window.ADRUM;b.a.M(document.cookie,document.referrer);b.command("mark","firstbyte",window["adrum-start-time"]);b.listenForErrors();b.addEventListener(window,"load",b.j);b.h()})(a||(a={}))}})();})();

